test-server:
  image: mcnaugho/dir
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database
    # - MONGODB_PORT
    - MONGODB_DATABASE=DIR
    - LOG_LEVEL=DEBUG
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command: /usr/local/bin/dir-exe
  ports:
    - "8082:8082"
  links:
    - database
database:
  image: mongo:3.0.2
